### ISSUE TITLE
Unable to load default module names

### ISSUE THREAD

**Issue by dynajoe** [nlf/lab-babel#1]
It's possible to automatically require `index.es` by doing the following: `require('./some/path')`

This will load the module located at `./some/path/index.es`

This is enabled by the require hook in babel js: https://babeljs.io/docs/usage/require/

Any thoughts on making this possible? How does it work with the source map stuff you're doing?

**Comment by phated** [comment]
This should be possible with versions of lab that wire up the require hooks.  We specify that extension at https://github.com/nlf/lab-babel/blob/master/lib/index.js#L20
