### ISSUE TITLE
Using pattern 'test'

### ISSUE THREAD

**Issue by mazzy89** [nlf/lab-babel#10]
I'm trying to use the pattern `test` in my test files along with the extension `.es` but it doesn't work. I call the test in this way:

`./node_modules/.bin/lab -v -T node_modules/lab-babel -P test -I __core-js_shared__`

it seems that it is not supported

one my sample file is named in this way: `file.test.es`

**Comment by phated** [comment]
Lab loads the files, not babel's require so custom extensions won't work.
