### ISSUE TITLE
different code coverage results with 1.0.0 and 1.0.1

### ISSUE THREAD

**Issue by robertkowalski** [nlf/lab-babel#3]
I just updated to 1.0.1 and getting a lot of strange code coverage errors,

I run: `lab -v --transform node_modules/lab-babel -t 100 -S`

I get:

```
No global variable leaks detected
Coverage: 99.18% (4/485)
src/cluster.js missing coverage from file(s):
    src/cluster.js on line(s): 212, 212
src/isonline.js missing coverage from file(s):
    src/isonline.js on line(s): 9
src/utils.js missing coverage from file(s):
    src/utils.js on line(s): 54
Code coverage below threshold: 99.18 < 100
```

now when I take a look in `src` util, line 54 is:

```
export function removeUsernamePw (u) {
```

line 212 in cluster.js is:

```
export function get (cluster, node) {
```

with 1.0.0 I still have 100% code coverage and I have tests for those functions, do you have an idea what's happening?

**Comment by jedireza** [comment]
@robertkowalski `lab@11.x` just got published and includes updates related to code coverage. Would you be willing to try out the latest version of `lab` and `lab-babel` to see if it resolves your issue?

**Comment by nlf** [comment]
thanks for the follow up @jedireza!

**Comment by robertkowalski** [comment]
thank you for your response! we switched to another testing lib end of 2015

because lab releases bring a lot of breaking changes i think it does not
make sense to check out the old code and update lab & lab-babel

On Mon, Aug 15, 2016 at 8:37 PM, Nathan LaFreniere <notifications@github.com
